### ISSUE TITLE
Add section on DMP + Data Sharing

### ISSUE THREAD

**Issue by RaoOfPhysics** [RaoOfPhysics/phd-starter-kit#12]
See https://twitter.com/shefw/status/667757087854739456

**Comment by jcolomb** [comment]
I will try to help when I find time...

**Comment by RaoOfPhysics** [comment]
Thanks, @jcolomb! I'm going to try and update all the text in the next couple of days (I'm on holiday and don't have to worry about work). Will be grateful if you could look at the changes in the PR I create. :)
