### ISSUE TITLE
Add overleaf in the list of latex tools.

### ISSUE THREAD

**Issue by jcolomb** [RaoOfPhysics/phd-starter-kit#15]
Do you mention Rstudio to be used to write markdown files?

**Comment by RaoOfPhysics** [comment]
Good call. I should ~~replace~~ remove Penflip (sadly, it hasn't been updated in ages). EDIT: I've already linked to Authorea and ShareLaTeX -- will link to Overleaf too.

Haven't mentioned RStudio, but will do so, somehow linking R with the Markdown section. Thanks for flagging this.
