### ISSUE TITLE
Inkscape for posters?

### ISSUE THREAD

**Issue by dotsdl** [RaoOfPhysics/phd-starter-kit#5]
Hey Rao,

Great list; I'm in my fourth year of a Ph.D. program and there's a lot of overlap between the tools you have found most useful and my own. I would add [Inkscape](https://inkscape.org/en/) to the list of software that's great for poster-making. I would recommend it for posters over a raster editor like GIMP because vector graphics are rescalalable, and a vector graphics editor allows you the flexibility to post-process components of plots produced by e.g. matplotlib, such as altering colors or adding annotation.

**Comment by RaoOfPhysics** [comment]
Hey @dotsdl!

Thanks for giving this a read and for your helpful comment. Inkscape was also mentioned to me by someone else, and I'll update the list to include it.

Cheers,
Achintya
